# Site settings
title: totuworld's tech blog
email: totuworld@gmail.com
description: Full 🥩🔥 Developer
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  totuworld
permalink: /:year/:month/:day/:title/

url: https://blog.totu.dev
author:
  twitter: totuworld

twitter:
  username: totuworld


# Build settings
markdown: kramdown

# highlight
# 本地用rouge, github上用pygments
# highlighter: rouge
# highlighter: rouge
highlighter: false

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true
  # https://github.com/jekyll/jekyll/pull/4090
  # syntax_highlighter: rouge

  # # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # # span, block element options fall back to global
  # syntax_highlighter_opts:
  #   # Rouge Options › https://github.com/jneen/rouge#full-options
  #   css_class: 'highlight'
  #   #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
  #   span:
  #     line_numbers: false
  #   block:
  #     line_numbers: true
  #     start_line: 1

gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll_github_sample

gist:
  noscript: false